<robot name="two_link_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="link_radius" value="0.1" />
  <xacro:property name="link_length" value="1.0" />

  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="1 1 1" />
      </geometry>
    </visual>
  </link>

  <joint name="joint1" type="revolute">
    <parent link="base_link"/>
    <child link="second_link"/>
    <origin xyz="0 0 0.5" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="1000" velocity="1.0" />
  </joint>

  <link name="second_link">
    <visual>
      <origin xyz="0 0 ${link_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${link_radius}" length="${link_length}" />
      </geometry>
    </visual>
  </link>

</robot>
